[package]
name = "task-hookrs"
version = "0.2.2"
authors = ["Matthias Beyer <mail@beyermatthias.de>",
           "Mario Krehl <mario-krehl@gmx.de>",
          ]

description = "Crate to work with taskwarrior exported JSON"
keywords = ["json", "taskwarrior", "todo", "import", "export"]

documentation = "https://matthiasbeyer.github.io/task-hookrs/task_hookrs/index.html"
homepage      = "https://github.com/matthiasbeyer/task-hookrs"
repository    = "https://github.com/matthiasbeyer/task-hookrs"
readme        = "./README.md"
license       = "MPL-2.0"

[dependencies]
chrono = "0.2"
log = "0.3"
serde = "0.8"
serde_json = "0.8"
uuid = { version = "0.3", features = ["serde"] }
itertools = "0.5"

[dev-dependencies]
env_logger = "0.3"

