on: [push, pull_request]

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: sudo apt-get update && sudo apt-get install -y taskwarrior
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - run: |
          # prepare taskwarrior, initial setup
          yes | task
          cargo run --example create_task | tee /tmp/create_task
          task import /tmp/create_task || exit 1
          cat /tmp/create_task | cargo run --example import_task || exit 1
